name: Scrape BNM FAST

on:
  schedule:
    - cron: "14 13 * * 1-5"
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install dependencies
        run: poetry install
      - name: Run Program
        run: poetry run python3 -m bnm_fast
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          files: output/*
      - name: Push new data files
        run: |
          git config --global user.name github-actions
          git config --global user.email ""
          git add .
          git commit -m "Updated with latest data from BNM FAST"
          git push